#!/usr/bin/env node

var packagejson = require(__dirname + '/../package.json');
var program = require('commander');
var _ = require('lodash');
var cargo = require('..');

program
    .version(packagejson.version)
    .description('Manage your infrastructure\'s services, manage services on the given metal')
    .arguments('<action> <metal> [service...]')
    .action(function (action, metal, services) {
        if (!_.isFunction(cargo.service[action])) {
            cargo.log('throw', 'The given action does not exist');
        }

        cargo.service[action](services, metal, function (output) {
            cargo.log('Finished', action, 'on', metal);
            if (output) {
                cargo.log('Output:\n');
                console.log(output);
            }
        })
    })
    .parse(process.argv);

if (!process.argv.slice(3).length) {
    program.help();
}
