#!/usr/bin/env node

var packagejson = require(__dirname + '/../package.json');
var program = require('commander');
var _ = require('lodash');
var cargo = require('..');

var shell = require('shelljs');

program
    .version(packagejson.version)
    .description('Runs setup tasks for all or particular codebases (paralell operation)')
    .arguments('<repo...>', 'The repo that you want to clone')
    .action(function (repos) {
        cargo.setup.run(repos, function () {
            cargo.log('Finished running setup tasks');
        });
    })
    .option('-D', '--dry-run', 'Perform a dry run install without changing any files.')
    .parse(process.argv);

if (!process.argv.slice(2).length) {
    program.help();
}
