#!/usr/bin/env node

var packagejson = require(__dirname + '/../package.json');
var program = require('commander');
var _ = require('lodash');
var cargo = require('..');

program
    .version(packagejson.version)
    .description('Initialise the nearest cargo configuration')
    .arguments('<repo...>', 'The repo that you want to init')
    .action(function (repos) {
        cargo.git.clone(repos, function () {
            cargo.log('Finished cloning repositories:', repos.join(', '));
            cargo.setup.run(repos, function () {
                cargo.log('Finished setting up repositories:', repos.join(', '));
            });
        });
    })
    .parse(process.argv);

if (!process.argv.slice(2).length) {
    program.help();
}
